### ISSUE TITLE
Setup Github Actions to validate file format

### ISSUE THREAD

**Issue by bhumijgupta** [bhumijgupta/Deno-news-cli#5]
Setup CI using Github Actions to enforce files are formatted according to `deno fmt --check`

Proposed config:
1. `runs-on: ubuntu-18.04`
2. Setup deno using [setup-deno](https://github.com/denolib/setup-deno#usage) action 
3. `run: deno fmt --check`

The action should run on every commit to the master branch

**Comment by CodeSadhu** [comment]
@bhumijgupta Do I need a Linux config to do this? Was willing to explore github actions...

**Comment by bhumijgupta** [comment]
No, you do not need a linux environment for coding it, but the github action should run in an `Ubuntu 18.04` environment. You can check out the official github action docs. They are quite helpful

**Comment by CodeSadhu** [comment]
@bhumijgupta Alright! Thanks.

**Comment by Gau02** [comment]
👋 @bhumijgupta, Could you please have a look at PR https://github.com/bhumijgupta/Deno-news-cli/pull/6 for this issue?

**Comment by bhumijgupta** [comment]
Closed via #6
